---
- name: Déploiement de l'application web statique
  hosts: all
  become: yes
  vars:
    app_source: "{{ playbook_dir }}/../app"
    app_dest: /var/www/html/tp-app
    server_ip: "{{ ansible_host }}"
    nginx_config_path: /etc/nginx/sites-available/tp-app.conf
    nginx_symlink_path: /etc/nginx/sites-enabled/tp-app.conf

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer le répertoire de destination de l'application
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers de l'application
      copy:
        src: "{{ app_source }}/"
        dest: "{{ app_dest }}/"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Déployer le fichier de configuration Nginx
      template:
        src: nginx_vhost.conf.j2
        dest: "{{ nginx_config_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Activer la configuration Nginx
      file:
        src: "{{ nginx_config_path }}"
        dest: "{{ nginx_symlink_path }}"
        state: link
        force: yes

    - name: Supprimer la configuration par défaut si présente
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted
