name: Secure Deployment Simulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simulate-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Vérifier que la clé privée SSH est valide et sans passphrase
      - name: Validate SSH private key format
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # Vérifie si c'est bien une clé privée SSH (contenu texte)
          if ! grep -q "PRIVATE KEY" key.pem; then
            echo "❌ Ce n'est pas une clé privée SSH valide"
            exit 1
          fi

          # Vérifie l'absence de passphrase
          if grep -q "ENCRYPTED" key.pem; then
            echo "❌ La clé est chiffrée avec une passphrase, ce n'est pas compatible avec un déploiement automatisé."
            exit 1
          fi

          echo "✅ Clé privée SSH valide et sans passphrase détectée"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Vérifier les variables d'environnement (simples et GitHub)
      - name: Check secret variables and environment
        run: |
          echo "📦 Vérification des variables d'environnement..."

          if [ -z "$SERVER_IP" ]; then
            echo "❌ SERVER_IP est vide"
            exit 1
          fi

          if [ -z "$SERVER_USER" ]; then
            echo "❌ SERVER_USER est vide"
            exit 1
          fi

          echo "🌐 SERVER_IP: $SERVER_IP"
          echo "👤 SERVER_USER: $SERVER_USER"
          echo "🖥️ Système runner GitHub : $RUNNER_OS"
          echo "✅ Secrets présents et format correct"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}

      # 4. Simulation de commandes SSH
      - name: Simulate SSH deployment commands
        run: |
          echo "🛠️ Simulation des commandes SSH qui seraient exécutées :"
          echo "ssh -i key.pem $SERVER_USER@$SERVER_IP 'mkdir -p /var/www/html/tp-app'"
          echo "ssh -i key.pem $SERVER_USER@$SERVER_IP 'sudo systemctl restart nginx'"
          echo "✅ Simulation SSH terminée (aucune connexion réelle effectuée)"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
