name: Secure Deployment Simulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simulate-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Vérifier que la clé privée SSH est correcte et sans passphrase
      - name: Validate SSH private key format
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          echo "📂 Premières lignes de la clé :"
          head -n 2 key.pem

          first_line=$(head -n 1 key.pem)

          if [[ "$first_line" != "-----BEGIN OPENSSH PRIVATE KEY-----" && "$first_line" != "-----BEGIN RSA PRIVATE KEY-----" ]]; then
            echo "❌ Clé non reconnue : début inattendu → '$first_line'"
            exit 1
          fi

          if grep -q "ENCRYPTED" key.pem; then
            echo "❌ La clé est chiffrée avec une passphrase, ce n'est pas compatible avec un déploiement automatisé."
            exit 1
          fi

          echo "✅ Clé privée SSH détectée et sans passphrase"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Vérifier que les autres secrets sont bien définis
      - name: Check secret variables
        run: |
          if [ -z "$SERVER_IP" ]; then
            echo "❌ SERVER_IP est vide"
            exit 1
          fi

          if [ -z "$SERVER_USER" ]; then
            echo "❌ SERVER_USER est vide"
            exit 1
          fi

          echo "🌍 SERVER_IP: $SERVER_IP"
          echo "👤 SERVER_USER: $SERVER_USER"
          echo "✅ Secrets valides"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}

      # 4. Simulation de commandes SSH (pas de connexions réelle)
      - name: Simulate SSH deployment
        run: |
          echo "🛠️ Simulation :"
          echo "ssh -i key.pem $SERVER_USER@$SERVER_IP 'mkdir -p /var/www/html/tp-app'"
          echo "ssh -i key.pem $SERVER_USER@$SERVER_IP 'sudo systemctl restart nginx'"
          echo "✅ Fin de la simulation"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
